// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIlg4k8N4d1bL5yCG6IzTr5WQLPzgBAcU',
    appId: '1:379965229909:web:e3ece0769046190b86bddc',
    messagingSenderId: '379965229909',
    projectId: 'funny-flower',
    authDomain: 'funny-flower.firebaseapp.com',
    storageBucket: 'funny-flower.firebasestorage.app',
    measurementId: 'G-FEEE9H54CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVY-Z5QVM_4KlljWyIfcOz4nG3gwSmOcg',
    appId: '1:379965229909:android:8ec74fbac04871d886bddc',
    messagingSenderId: '379965229909',
    projectId: 'funny-flower',
    storageBucket: 'funny-flower.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE2GiImXwPiYpVmFwFBlPRj8iH9HdTXPI',
    appId: '1:379965229909:ios:27138a4cbb22721186bddc',
    messagingSenderId: '379965229909',
    projectId: 'funny-flower',
    storageBucket: 'funny-flower.firebasestorage.app',
    iosBundleId: 'com.example.funnyFlower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE2GiImXwPiYpVmFwFBlPRj8iH9HdTXPI',
    appId: '1:379965229909:ios:27138a4cbb22721186bddc',
    messagingSenderId: '379965229909',
    projectId: 'funny-flower',
    storageBucket: 'funny-flower.firebasestorage.app',
    iosBundleId: 'com.example.funnyFlower',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIlg4k8N4d1bL5yCG6IzTr5WQLPzgBAcU',
    appId: '1:379965229909:web:b12592a0f25758b986bddc',
    messagingSenderId: '379965229909',
    projectId: 'funny-flower',
    authDomain: 'funny-flower.firebaseapp.com',
    storageBucket: 'funny-flower.firebasestorage.app',
    measurementId: 'G-MSJML287RJ',
  );
}
